// 塔罗牌数据 - 78张牌
const TAROT_CARDS = [
  // ===== 大阿尔卡纳 (22张) =====
  { id: 0, name: "愚者", nameEn: "The Fool", arcana: "major", number: 0,
    keywords: "开始, 天真, 冒险, 自由",
    meaning: "新的开始，保持开放心态，信任过程。象征纯真与无限可能。",
    meaningRev: "鲁莽行事，缺乏判断，风险过大。需要三思而后行。" },
  { id: 1, name: "魔术师", nameEn: "The Magician", arcana: "major", number: 1,
    keywords: "创造, 技能, 自信, 资源",
    meaning: "你拥有实现目标所需的一切资源。发挥你的技能与创造力。",
    meaningRev: "才能浪费，操控他人，方向不明。重新审视你的手段。" },
  { id: 2, name: "女祭司", nameEn: "The High Priestess", arcana: "major", number: 2,
    keywords: "直觉, 潜意识, 神秘, 内在",
    meaning: "倾听你的直觉和内在的声音。答案隐藏在潜意识中。",
    meaningRev: "忽视直觉，秘密被揭露，表面化。需要回归内心。" },
  { id: 3, name: "女皇", nameEn: "The Empress", arcana: "major", number: 3,
    keywords: "丰饶, 自然, 母性, 舒适",
    meaning: "丰饶与成长。享受生活中的美好，滋养自己和他人。",
    meaningRev: "创造力受阻，依赖他人，忽视自我。重新与自然连接。" },
  { id: 4, name: "皇帝", nameEn: "The Emperor", arcana: "major", number: 4,
    keywords: "权威, 秩序, 稳定, 纪律",
    meaning: "建立秩序与结构。用权威和纪律保护你的领域。",
    meaningRev: "专制，僵化，缺乏领导力。需要更灵活的掌控方式。" },
  { id: 5, name: "教皇", nameEn: "The Hierophant", arcana: "major", number: 5,
    keywords: "传统, 教诲, 信仰, 指导",
    meaning: "寻求精神导师或传统智慧的指引。遵循规范与仪式。",
    meaningRev: "反抗常规，挑战权威。需要找到自己的精神道路。" },
  { id: 6, name: "恋人", nameEn: "The Lovers", arcana: "major", number: 6,
    keywords: "爱情, 选择, 和谐, 关系",
    meaning: "重要的选择与结合。跟随内心做出的决定将带来和谐。",
    meaningRev: "关系失衡，错误选择，价值观冲突。重新审视承诺。" },
  { id: 7, name: "战车", nameEn: "The Chariot", arcana: "major", number: 7,
    keywords: "意志, 胜利, 决心, 征服",
    meaning: "凭借坚定的意志力征服挑战。控制对立的力量取得胜利。",
    meaningRev: "失控，缺乏方向，侵略性。需要重新掌控局面。" },
  { id: 8, name: "力量", nameEn: "Strength", arcana: "major", number: 8,
    keywords: "勇气, 毅力, 内在力量, 温柔",
    meaning: "用内心的勇气和温柔面对困难。真正的力量来自爱与耐心。",
    meaningRev: "自我怀疑，软弱，缺乏自信。找回你的内在力量。" },
  { id: 9, name: "隐士", nameEn: "The Hermit", arcana: "major", number: 9,
    keywords: "内省, 独处, 智慧, 指引",
    meaning: "暂时退隐，寻求内在的智慧。孤独中蕴藏着启迪。",
    meaningRev: "孤立过度，拒绝帮助，迷路。需要适度寻求外界。" },
  { id: 10, name: "命运之轮", nameEn: "Wheel of Fortune", arcana: "major", number: 10,
    keywords: "变化, 循环, 命运, 契机",
    meaning: "命运的轮盘开始转动。变化即将到来，抓住新的机遇。",
    meaningRev: "运气不佳，抗拒变化，打破循环。消极期终将过去。" },
  { id: 11, name: "正义", nameEn: "Justice", arcana: "major", number: 11,
    keywords: "公平, 真相, 因果, 平衡",
    meaning: "因果报应，公平裁决。真相终将大白，行动必有结果。",
    meaningRev: "不公，逃避责任，失衡。需要诚实地面对自己。" },
  { id: 12, name: "倒吊人", nameEn: "The Hanged Man", arcana: "major", number: 12,
    keywords: "牺牲, 暂停, 换位思考, 放手",
    meaning: "暂停视角，换位思考。有时候需要放手才能获得。",
    meaningRev: "拖延，抗拒牺牲，停滞不前。需要改变视角。" },
  { id: 13, name: "死神", nameEn: "Death", arcana: "major", number: 13,
    keywords: "结束, 转变, 放下, 新生",
    meaning: "旧篇章的结束，新篇章的开始。放下无法再服务你的东西。",
    meaningRev: "抗拒改变，停滞，恐惧未知。拥抱必要的转变。" },
  { id: 14, name: "节制", nameEn: "Temperance", arcana: "major", number: 14,
    keywords: "平衡, 节制, 耐心, 调和",
    meaning: "寻找平衡与中庸之道。耐心调和生活中的对立面。",
    meaningRev: "极端，失衡，缺乏耐心。需要重新找到平衡点。" },
  { id: 15, name: "恶魔", nameEn: "The Devil", arcana: "major", number: 15,
    keywords: "束缚, 欲望, 物质, 成瘾",
    meaning: "面对你的阴影面。被物质欲望或不良习惯所束缚。",
    meaningRev: "挣脱束缚，觉醒，拒绝诱惑。正在获得自由。" },
  { id: 16, name: "高塔", nameEn: "The Tower", arcana: "major", number: 16,
    keywords: "颠覆, 突变, 觉醒, 重建",
    meaning: "突如其来的变化与崩塌。拆除虚假的根基才能重建。",
    meaningRev: "避免灾难，抗拒必要的变化。延迟的觉醒。" },
  { id: 17, name: "星星", nameEn: "The Star", arcana: "major", number: 17,
    keywords: "希望, 灵感, 宁静, 治愈",
    meaning: "希望与启示。在黑暗中找到光明，信念带来治愈。",
    meaningRev: "绝望，失去信念，创意枯竭。需要重新找回希望。" },
  { id: 18, name: "月亮", nameEn: "The Moon", arcana: "major", number: 18,
    keywords: "幻象, 恐惧, 潜意识, 不安",
    meaning: "事物并非表面所见。面对你的恐惧，探索潜意识。",
    meaningRev: "释放恐惧，幻觉消散，开始看清真相。" },
  { id: 19, name: "太阳", nameEn: "The Sun", arcana: "major", number: 19,
    keywords: "喜悦, 成功, 活力, 光明",
    meaning: "光明与成功。快乐和活力充满你的生活。一切都很美好。",
    meaningRev: "暂时的阴霾，快乐受阻，小挫折。阳光很快会回来。" },
  { id: 20, name: "审判", nameEn: "Judgement", arcana: "major", number: 20,
    keywords: "重生, 觉醒, 审判, 宽恕",
    meaning: "内心的召唤与觉醒。是时候为过去做出审判，迎接新生。",
    meaningRev: "自我怀疑，拒绝召唤，惧怕评判。需要自我接纳。" },
  { id: 21, name: "世界", nameEn: "The World", arcana: "major", number: 21,
    keywords: "完成, 成就, 圆满, 旅行",
    meaning: "圆满完成。一个周期的结束，庆祝你的成就与成长。",
    meaningRev: "未完成，延迟，缺乏圆满感。需要耐心完成最后一步。" },

  // ===== 权杖组 (Wands) - 火元素 =====
  { id: 22, name: "权杖王牌", nameEn: "Ace of Wands", arcana: "minor", suit: "wands", number: "Ace",
    keywords: "开始, 灵感, 创造, 新项目",
    meaning: "创意的火花。新的项目、热情或冒险的开始。",
    meaningRev: "创意受阻，缺乏方向，延迟的开始。" },
  { id: 23, name: "权杖二", nameEn: "Two of Wands", arcana: "minor", suit: "wands", number: "2",
    keywords: "规划, 决策, 未来, 探索",
    meaning: "做出重要的决策。规划未来，探索新的可能性。",
    meaningRev: "恐惧未知，缺乏规划，优柔寡断。" },
  { id: 24, name: "权杖三", nameEn: "Three of Wands", arcana: "minor", suit: "wands", number: "3",
    keywords: "远见, 扩展, 探索, 贸易",
    meaning: "扩展视野。你的计划开始看到成果，继续前进。",
    meaningRev: "挫折，延迟，缺乏远见。需要重新调整计划。" },
  { id: 25, name: "权杖四", nameEn: "Four of Wands", arcana: "minor", suit: "wands", number: "4",
    keywords: "庆祝, 和谐, 家, 团聚",
    meaning: "庆祝与团聚。家庭和谐，实现阶段性目标。",
    meaningRev: "缺乏稳定，家庭矛盾，取消庆祝。" },
  { id: 26, name: "权杖五", nameEn: "Five of Wands", arcana: "minor", suit: "wands", number: "5",
    keywords: "竞争, 冲突, 分歧, 能量",
    meaning: "竞争与冲突。不同的意见在碰撞，但这是成长的动力。",
    meaningRev: "回避冲突，内斗，和解的开端。" },
  { id: 27, name: "权杖六", nameEn: "Six of Wands", arcana: "minor", suit: "wands", number: "6",
    keywords: "胜利, 认可, 赞誉, 好消息",
    meaning: "获得认可与胜利。你的努力得到肯定，好消息传来。",
    meaningRev: "失败，缺乏认可，自大。保持谦逊。" },
  { id: 28, name: "权杖七", nameEn: "Seven of Wands", arcana: "minor", suit: "wands", number: "7",
    keywords: "防御, 坚持, 挑战, 维护",
    meaning: "坚守立场。面对挑战时保持勇气，捍卫你的信念。",
    meaningRev: "不堪重负，放弃，丧失优势。" },
  { id: 29, name: "权杖八", nameEn: "Eight of Wands", arcana: "minor", suit: "wands", number: "8",
    keywords: "速度, 行动, 进展, 通讯",
    meaning: "快速进展。事情在加速，沟通顺畅，好消息快到了。",
    meaningRev: "延迟，沟通不畅，慢下来。需要耐心等待。" },
  { id: 30, name: "权杖九", nameEn: "Nine of Wands", arcana: "minor", suit: "wands", number: "9",
    keywords: "韧性, 坚持, 警觉, 边界",
    meaning: "最后的坚持。你已经走了很长的路，再坚持一下。",
    meaningRev: "筋疲力尽，放弃，偏执。需要休息。" },
  { id: 31, name: "权杖十", nameEn: "Ten of Wands", arcana: "minor", suit: "wands", number: "10",
    keywords: "负担, 压力, 责任, 劳碌",
    meaning: "承担过多责任。压力很大，需要学会委派和放手。",
    meaningRev: "卸下负担，委派任务，承认极限。" },
  { id: 32, name: "权杖侍从", nameEn: "Page of Wands", arcana: "minor", suit: "wands", number: "Page",
    keywords: "探索, 热情, 消息, 新生",
    meaning: "新的消息与灵感。充满热情地探索新的可能性。",
    meaningRev: "缺乏方向，拖延，消息延迟。" },
  { id: 33, name: "权杖骑士", nameEn: "Knight of Wands", arcana: "minor", suit: "wands", number: "Knight",
    keywords: "冒险, 冲动, 旅行, 激情",
    meaning: "充满激情的行动。追求冒险，勇敢地追逐目标。",
    meaningRev: "冲动行事，缺乏计划，半途而废。" },
  { id: 34, name: "权杖王后", nameEn: "Queen of Wands", arcana: "minor", suit: "wands", number: "Queen",
    keywords: "自信, 热情, 魅力, 领导",
    meaning: "自信而有魅力。用你的热情和温暖感染他人。",
    meaningRev: "嫉妒，缺乏自信，控制欲强。" },
  { id: 35, name: "权杖国王", nameEn: "King of Wands", arcana: "minor", suit: "wands", number: "King",
    keywords: "领袖, 愿景, 企业家, 荣誉",
    meaning: "天生的领袖。有远见，有魄力，带领他人走向成功。",
    meaningRev: "专横，不切实际，滥用权力。" },

  // ===== 圣杯组 (Cups) - 水元素 =====
  { id: 36, name: "圣杯王牌", nameEn: "Ace of Cups", arcana: "minor", suit: "cups", number: "Ace",
    keywords: "爱, 情感, 直觉, 新关系",
    meaning: "情感的开启。新的爱情、友谊或情感连接的开始。",
    meaningRev: "情感空虚，爱被阻塞，压抑感受。" },
  { id: 37, name: "圣杯二", nameEn: "Two of Cups", arcana: "minor", suit: "cups", number: "2",
    keywords: "结合, 吸引力, 爱, 合作",
    meaning: "真心的连接。相爱或深度合作关系的确立。",
    meaningRev: "关系失衡，分离，沟通不良。" },
  { id: 38, name: "圣杯三", nameEn: "Three of Cups", arcana: "minor", suit: "cups", number: "3",
    keywords: "友谊, 庆祝, 欢乐, 社交",
    meaning: "庆祝与友谊。与朋友相聚，分享喜悦与欢乐。",
    meaningRev: "过度放纵，孤立，社交焦虑。" },
  { id: 39, name: "圣杯四", nameEn: "Four of Cups", arcana: "minor", suit: "cups", number: "4",
    keywords: "沉思, 漠然, 冥想, 内省",
    meaning: "对现状不满。需要内省，发现被忽视的机会。",
    meaningRev: "重新觉醒，开始行动，接受新机会。" },
  { id: 40, name: "圣杯五", nameEn: "Five of Cups", arcana: "minor", suit: "cups", number: "5",
    keywords: "失落, 悲伤, 遗憾, 原谅",
    meaning: "悲伤与失落。专注于失去的，却忽略了还拥有的。",
    meaningRev: "接受过去，向前看，宽恕与释怀。" },
  { id: 41, name: "圣杯六", nameEn: "Six of Cups", arcana: "minor", suit: "cups", number: "6",
    keywords: "回忆, 童年, 纯真, 赠予",
    meaning: "怀旧与回忆。过去的馈赠或与故人重逢。",
    meaningRev: "活在过去，无法前进，成熟与放下。" },
  { id: 42, name: "圣杯七", nameEn: "Seven of Cups", arcana: "minor", suit: "cups", number: "7",
    keywords: "幻象, 选择, 幻想, 迷失",
    meaning: "面对众多选择。区分幻想与现实，做出清醒的决定。",
    meaningRev: "清晰的选择，聚焦目标，摆脱幻想。" },
  { id: 43, name: "圣杯八", nameEn: "Eight of Cups", arcana: "minor", suit: "cups", number: "8",
    keywords: "放手, 追寻, 放弃, 旅程",
    meaning: "离开不再满足你的东西。追寻更深层的意义。",
    meaningRev: "恐惧改变，盲目坚持，迷失方向。" },
  { id: 44, name: "圣杯九", nameEn: "Nine of Cups", arcana: "minor", suit: "cups", number: "9",
    keywords: "满足, 愿望, 快乐, 满足",
    meaning: "愿望成真。满足与快乐，你值得拥有这一切。",
    meaningRev: "不满，物质主义，内心空虚。" },
  { id: 45, name: "圣杯十", nameEn: "Ten of Cups", arcana: "minor", suit: "cups", number: "10",
    keywords: "幸福, 家庭, 和谐, 圆满",
    meaning: "情感圆满。家庭幸福，和谐美满的生活。",
    meaningRev: "家庭不和，破碎的梦想，关系紧张。" },
  { id: 46, name: "圣杯侍从", nameEn: "Page of Cups", arcana: "minor", suit: "cups", number: "Page",
    keywords: "直觉, 消息, 创意, 情感",
    meaning: "情感的消息。创意的灵感或情感方面的新消息。",
    meaningRev: "情感不成熟，创意受阻，坏消息。" },
  { id: 47, name: "圣杯骑士", nameEn: "Knight of Cups", arcana: "minor", suit: "cups", number: "Knight",
    keywords: "浪漫, 想象, 追求, 邀请",
    meaning: "浪漫的追求。追随你的心，向梦想前进。",
    meaningRev: "幻想破灭，嫉妒，情绪化。" },
  { id: 48, name: "圣杯王后", nameEn: "Queen of Cups", arcana: "minor", suit: "cups", number: "Queen",
    keywords: "关怀, 直觉, 滋养, 敏感",
    meaning: "富有同情心的关怀。用爱和直觉滋养身边的人。",
    meaningRev: "情感依赖，过度敏感，自我牺牲。" },
  { id: 49, name: "圣杯国王", nameEn: "King of Cups", arcana: "minor", suit: "cups", number: "King",
    keywords: "情感成熟, 智慧, 冷静, 慈悲",
    meaning: "情感与智慧的平衡。以慈悲和冷静领导他人。",
    meaningRev: "情感压抑，情绪失控，冷酷无情。" },

  // ===== 宝剑组 (Swords) - 风元素 =====
  { id: 50, name: "宝剑王牌", nameEn: "Ace of Swords", arcana: "minor", suit: "swords", number: "Ace",
    keywords: "真理, 清晰, 智慧, 突破",
    meaning: "思想的突破。清晰的思维，真理与正义。",
    meaningRev: "混乱，错误判断，信息不实。" },
  { id: 51, name: "宝剑二", nameEn: "Two of Swords", arcana: "minor", suit: "swords", number: "2",
    keywords: "抉择, 僵局, 回避, 平衡",
    meaning: "艰难的抉择。闭眼逃避事实，需要做出决定。",
    meaningRev: "无法抉择，信息不足，真相浮现。" },
  { id: 52, name: "宝剑三", nameEn: "Three of Swords", arcana: "minor", suit: "swords", number: "3",
    keywords: "心痛, 悲伤, 真相, 释放",
    meaning: "心碎与痛苦。令人痛苦的事实，但释放是治愈的开始。",
    meaningRev: "恢复，释放悲伤，宽恕。" },
  { id: 53, name: "宝剑四", nameEn: "Four of Swords", arcana: "minor", suit: "swords", number: "4",
    keywords: "休息, 冥想, 恢复, 放松",
    meaning: "需要休息。给自己时间恢复和沉思。",
    meaningRev: "无法休息，焦虑，康复缓慢。" },
  { id: 54, name: "宝剑五", nameEn: "Five of Swords", arcana: "minor", suit: "swords", number: "5",
    keywords: "冲突, 损失, 胜利, 屈辱",
    meaning: "有胜算的冲突。赢了战役却输了人心。",
    meaningRev: "和解，妥协，放下过去的冲突。" },
  { id: 55, name: "宝剑六", nameEn: "Six of Swords", arcana: "minor", suit: "swords", number: "6",
    keywords: "过渡, 变化, 旅程, 释然",
    meaning: "过渡与前行。穿越困难的水域，走向更好的地方。",
    meaningRev: "被困在过去，抗拒变化。" },
  { id: 56, name: "宝剑七", nameEn: "Seven of Swords", arcana: "minor", suit: "swords", number: "7",
    keywords: "欺骗, 策略, 隐瞒, 孤立",
    meaning: "慎防欺骗。小心隐瞒的策略或不诚实的行动。",
    meaningRev: "坦白，弥补，被揭穿。" },
  { id: 57, name: "宝剑八", nameEn: "Eight of Swords", arcana: "minor", suit: "swords", number: "8",
    keywords: "束缚, 困境, 自我限制, 无助",
    meaning: "感觉被困住了。限制多数来自你自己的思维。",
    meaningRev: "解放，新视角，突破自我限制。" },
  { id: 58, name: "宝剑九", nameEn: "Nine of Swords", arcana: "minor", suit: "swords", number: "9",
    keywords: "焦虑, 噩梦, 担忧, 失眠",
    meaning: "恐惧与焦虑。担心最坏的情况，但多数只是心理作祟。",
    meaningRev: "释放焦虑，找回希望，心理治愈。" },
  { id: 59, name: "宝剑十", nameEn: "Ten of Swords", arcana: "minor", suit: "swords", number: "10",
    keywords: "终结, 失败, 痛苦, 再生",
    meaning: "最糟糕的时刻已经过去。虽痛苦但黎明即将到来。",
    meaningRev: "触底反弹，学习教训，缓慢恢复。" },
  { id: 60, name: "宝剑侍从", nameEn: "Page of Swords", arcana: "minor", suit: "swords", number: "Page",
    keywords: "好奇, 沟通, 警觉, 学习",
    meaning: "求知与探索。渴望学习新的知识和资讯。",
    meaningRev: "口舌之争，沟通不畅，轻率发言。" },
  { id: 61, name: "宝剑骑士", nameEn: "Knight of Swords", arcana: "minor", suit: "swords", number: "Knight",
    keywords: "行动, 果断, 冲动, 直率",
    meaning: "果断的行动。以速度和决心追求目标。",
    meaningRev: "鲁莽，冲动，缺乏策略。" },
  { id: 62, name: "宝剑王后", nameEn: "Queen of Swords", arcana: "minor", suit: "swords", number: "Queen",
    keywords: "清晰, 诚实, 独立, 洞察",
    meaning: "清晰与诚实。以敏锐的洞察力看待事物。",
    meaningRev: "刻薄，冷漠，过度批判。" },
  { id: 63, name: "宝剑国王", nameEn: "King of Swords", arcana: "minor", suit: "swords", number: "King",
    keywords: "权威, 真理, 公正, 理性",
    meaning: "理性与权威。以清晰的分析和公正的态度领导。",
    meaningRev: "滥用权力，独裁，冷酷的判断。" },

  // ===== 星币组 (Pentacles) - 土元素 =====
  { id: 64, name: "星币王牌", nameEn: "Ace of Pentacles", arcana: "minor", suit: "pentacles", number: "Ace",
    keywords: "机遇, 财富, 繁荣, 新开始",
    meaning: "物质的新开始。财务机会或新的职业规划。",
    meaningRev: "错失机会，财务损失，计划延迟。" },
  { id: 65, name: "星币二", nameEn: "Two of Pentacles", arcana: "minor", suit: "pentacles", number: "2",
    keywords: "平衡, 适应, 多任务, 资源",
    meaning: "平衡多重任务。灵活应对变化，管理好有限资源。",
    meaningRev: "不堪重负，财务失衡，混乱。" },
  { id: 66, name: "星币三", nameEn: "Three of Pentacles", arcana: "minor", suit: "pentacles", number: "3",
    keywords: "团队, 协作, 技能, 学习",
    meaning: "团队合作。一起学习、成长、打造更好的成果。",
    meaningRev: "缺乏团队精神，技能不足，质量下降。" },
  { id: 67, name: "星币四", nameEn: "Four of Pentacles", arcana: "minor", suit: "pentacles", number: "4",
    keywords: "保守, 节俭, 控制, 小气",
    meaning: "紧抓不放。对财务或资源的过度保护与吝啬。",
    meaningRev: "过度慷慨，财务失控，放手部分。" },
  { id: 68, name: "星币五", nameEn: "Five of Pentacles", arcana: "minor", suit: "pentacles", number: "5",
    keywords: "贫困, 困难, 孤立, 失落",
    meaning: "物质困难。感觉被排斥在外，需要寻求帮助。",
    meaningRev: "摆脱困境，找到帮助，改善财务。" },
  { id: 69, name: "星币六", nameEn: "Six of Pentacles", arcana: "minor", suit: "pentacles", number: "6",
    keywords: "慷慨, 慈善, 分享, 帮助",
    meaning: "给予与接受。慷慨地分享你的财富和资源。",
    meaningRev: "不公平，债务，片面接受。" },
  { id: 70, name: "星币七", nameEn: "Seven of Pentacles", arcana: "minor", suit: "pentacles", number: "7",
    keywords: "耐心, 投资, 评估, 收获",
    meaning: "等待收获。辛勤工作后的评估与耐心等待。",
    meaningRev: "投资回报差，失去耐心，浪费。" },
  { id: 71, name: "星币八", nameEn: "Eight of Pentacles", arcana: "minor", suit: "pentacles", number: "8",
    keywords: "专注, 技能, 勤奋, 工匠",
    meaning: "专注于技艺。勤奋学习，磨练技能。",
    meaningRev: "粗心，缺乏动力，低质量工作。" },
  { id: 72, name: "星币九", nameEn: "Nine of Pentacles", arcana: "minor", suit: "pentacles", number: "9",
    keywords: "独立, 富足, 自律, 精致",
    meaning: "自给自足。通过自律实现了物质和精神上的独立。",
    meaningRev: "依赖他人，财务危机，自我怀疑。" },
  { id: 73, name: "星币十", nameEn: "Ten of Pentacles", arcana: "minor", suit: "pentacles", number: "10",
    keywords: "传承, 家族, 财富, 长久",
    meaning: "世代传承。家族的财富与传统的延续。",
    meaningRev: "家族纷争，破产，传承断裂。" },
  { id: 74, name: "星币侍从", nameEn: "Page of Pentacles", arcana: "minor", suit: "pentacles", number: "Page",
    keywords: "学习, 实践, 勤奋, 消息",
    meaning: "务实的学习。新的技能或财务消息。",
    meaningRev: "拖延，缺乏计划，学习受阻。" },
  { id: 75, name: "星币骑士", nameEn: "Knight of Pentacles", arcana: "minor", suit: "pentacles", number: "Knight",
    keywords: "可靠, 勤奋, 稳健, 耐心",
    meaning: "踏实的行动。认真负责，一步一个脚印向前。",
    meaningRev: "懒惰，停滞，固执不变。" },
  { id: 76, name: "星币王后", nameEn: "Queen of Pentacles", arcana: "minor", suit: "pentacles", number: "Queen",
    keywords: "滋养, 务实, 富足, 自然",
    meaning: "务实而富饶的关怀。将物质安全与温暖结合。",
    meaningRev: "忽视自我，财务焦虑，物质主义。" },
  { id: 77, name: "星币国王", nameEn: "King of Pentacles", arcana: "minor", suit: "pentacles", number: "King",
    keywords: "成功, 财富, 领导, 商业",
    meaning: "物质的成功。富有的商业领袖，稳重而成功。",
    meaningRev: "贪婪，挥霍，财务管理不善。" }
];

// 获取单张牌
function getCard(cardId) {
  return TAROT_CARDS.find(c => c.id === cardId);
}

// 洗牌
function shuffleDeck() {
  const deck = [...TAROT_CARDS];
  for (let i = deck.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }
  return deck;
}

// 抽牌（带正逆位）
function drawCards(count) {
  const shuffled = shuffleDeck();
  const drawn = [];
  for (let i = 0; i < count && i < shuffled.length; i++) {
    const card = { ...shuffled[i] };
    card.isReversed = Math.random() < 0.5;
    drawn.push(card);
  }
  return drawn;
}

// 牌阵定义
const SPREADS = {
  single: {
    name: "单张占卜",
    nameEn: "Single Card",
    desc: "适合日常指南或快速解答简单问题",
    positions: [{ name: "今日指引" }]
  },
  three: {
    name: "三张牌阵",
    nameEn: "Three Cards",
    desc: "经典的三张牌展开，分析时间线或问题结构",
    positions: [
      { name: "过去" },
      { name: "现在" },
      { name: "未来" }
    ]
  },
  celtic: {
    name: "凯尔特十字",
    nameEn: "Celtic Cross",
    desc: "最全面的牌阵，深度分析问题的各个方面",
    positions: [
      { name: "当前状况" },
      { name: "面临的挑战" },
      { name: "过去的根基" },
      { name: "最近的过去" },
      { name: "最好的可能" },
      { name: "未来的发展" },
      { name: "你的态度" },
      { name: "环境因素" },
      { name: "希望与恐惧" },
      { name: "最终结果" }
    ]
  },
  love: {
    name: "爱情牌阵",
    nameEn: "Love Spread",
    desc: "专门分析感情关系的牌阵",
    positions: [
      { name: "你的感受" },
      { name: "对方的感受" },
      { name: "关系现状" },
      { name: "阻碍" },
      { name: "建议" }
    ]
  },
  career: {
    name: "事业牌阵",
    nameEn: "Career Spread",
    desc: "分析职业发展和事业方向",
    positions: [
      { name: "当前状况" },
      { name: "目标" },
      { name: "优势" },
      { name: "挑战" },
      { name: "建议" }
    ]
  }
};

if (typeof module !== 'undefined') module.exports = { TAROT_CARDS, SPREADS, shuffleDeck, drawCards, getCard };
